#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom dplyr bind_rows
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr last_col
#' @importFrom dplyr mutate
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr rename_with
#' @importFrom dplyr select
#' @importFrom dplyr slice_head
#' @importFrom dplyr summarise
#' @importFrom furrr future_map
#' @importFrom future plan
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 coord_fixed
#' @importFrom ggplot2 Geom
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 ggproto
#' @importFrom ggplot2 ggproto_parent
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 layer
#' @importFrom ggplot2 scale_alpha
#' @importFrom ggplot2 scale_color_gradientn
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 scale_fill_gradientn
#' @importFrom ggplot2 scale_fill_manual
#' @importFrom ggplot2 scale_size
#' @importFrom ggplot2 theme_void
#' @importFrom ggplot2 xlim
#' @importFrom ggplot2 ylim
#' @importFrom ggraph geom_node_point
#' @importFrom ggraph ggraph
#' @importFrom ggraph scale_edge_alpha
#' @importFrom ggraph scale_edge_color_gradientn
#' @importFrom ggraph scale_edge_color_manual
#' @importFrom ggraph theme_graph
#' @importFrom grDevices colorRampPalette
#' @importFrom grid arrow
#' @importFrom grid editGrob
#' @importFrom grid grobName
#' @importFrom grid rasterGrob
#' @importFrom grid unit
#' @importFrom grid viewport
#' @importFrom magrittr %<>%
#' @importFrom magrittr %>%
#' @importFrom purrr map
#' @importFrom RColorBrewer brewer.pal
#' @importFrom rlang .data
#' @importFrom scales alpha
#' @importFrom scales hue_pal
#' @importFrom SingleCellExperiment colData
#' @importFrom SingleCellExperiment rowData
#' @importFrom SpatialExperiment imgRaster
#' @importFrom SpatialExperiment scaleFactors
#' @importFrom SpatialExperiment spatialCoords
#' @importFrom stats dist
#' @importFrom stats median
#' @importFrom stats sd
#' @importFrom stats setNames
#' @importFrom SummarizedExperiment assays
#' @importFrom tibble as_tibble
#' @importFrom tibble tibble
#' @importFrom tibble tibble_row
#' @importFrom tidygraph activate
#' @importFrom tidygraph as_tbl_graph
#' @importFrom tidygraph filter
#' @importFrom tidygraph graph_adhesion
#' @importFrom tidygraph graph_clique_count
#' @importFrom tidygraph graph_clique_num
#' @importFrom tidygraph graph_component_count
#' @importFrom tidygraph graph_diameter
#' @importFrom tidygraph graph_girth
#' @importFrom tidygraph graph_mean_dist
#' @importFrom tidygraph graph_motif_count
#' @importFrom tidygraph graph_order
#' @importFrom tidygraph graph_reciprocity
#' @importFrom tidygraph graph_size
#' @importFrom tidygraph group_components
#' @importFrom tidygraph left_join
#' @importFrom tidygraph mutate
#' @importFrom tidygraph pull
#' @importFrom tidygraph select
#' @importFrom tidygraph to_components
#' @importFrom tidygraph to_undirected
#' @importFrom tidygraph unmorph
#' @importFrom tidyr pivot_longer
#' @importFrom tidyselect all_of
#' @importFrom tidyselect starts_with
#' @importFrom utils combn
## usethis namespace: end
NULL
